### ISSUE TITLE
Request for impementation of RFC 0003 Buildpack.yml to Environment Variables 

### ISSUE THREAD

**Issue by wburningham** [paketo-buildpacks/go-build#106]
## Unable to configure build pack via ENV variables

I'm in the process of migrating my company's Go build scripts (about 40 repos) over to buildpacks. At build time we dynamically inject build information into the built binaries/services using the `'-ldflags="-X main.variable=some-value"'`. Since the values of the build information are generated dynamically at build time the existing process of using a static build.env in a project descriptor will not work.

Many of the Go build scripts also have a config file (in an internal/proprietary format) that allows users to specify build targets. We will need to migrate these targets to a buildpack compatible format. Rather than migrating to use the supported buildpack.yml format, we'd prefer to standardize around ENV variables.

## Build Configuration

Please provide some details about your build configuration.

* What platform? `pack version 0.14.2+git-0fd189d.build-1450`

* What buildpacks are you using? `paketo-buildpacks/go version 0.2.8`

* What builder are you using? `paketobuildpacks/builder:tiny`

* Can you provide a sample app or relevant configuration? (nothing special)
```[project]
id = "cnb/demo-app"
name = "Demo App"
version = "1.0.0"
```

## Checklist

Please confirm the following:

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

This would greatly unblock me from migrating our company to buildpacks.

**Comment by fg-j** [comment]
(This is a request to implement #76; linking here for ease.)

**Comment by wburningham** [comment]
@ForestEckhardt, @ryanmoran would you accept a PR if I created one to add support for the ENV specified in the spec?

**Comment by ForestEckhardt** [comment]
@wburningham I just opened PR #109 that should do this. Sorry it took so long.

**Comment by wburningham** [comment]
No Problem. Thanks for working on it. I'll look at the PR for my own personal learning to compare how you did it with what I was thinking in my head.
