### ISSUE TITLE
BP_GO_BUILD_FLAGS does not seem to support innerquotes on flag values.

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/go-build#129]
## What happened?

* What were you attempting to do?

Trying to build a go app with the following:
```
pack build my-app --verbose --env BP_GO_BUILD_FLAGS='-ldflags="-extldflags -f no-PIC -static" -tags=osusergo,netgo,embedfs'
```

* What did you expect to happen?

I expected the image to be built.

* What was the actual behavior? Please provide log output, if possible.

```
[builder] Paketo Go Build Buildpack 0.2.2
[builder]   Executing build process
[builder]     Running 'go build -o /layers/paketo-buildpacks_go-build/targets/bin "-ldflags=-extldflags -f no-PIC -static" -tags=osusergo,netgo,embedfs -buildmode pie ./cmd/my-app'
[builder] failed to execute 'go build': exit status 2
[builder]       Failed after 21.136s
[builder]         # github.com/APP
[builder]         usage: link [options] main.o
[builder]           -B note
[builder]             	add an ELF NT_GNU_BUILD_ID note when using ELF
[builder]           -E entry
[builder]             	set entry symbol name
[builder]           -H type
[builder]             	set header type
[builder]           -I linker
[builder]             	use linker as ELF dynamic linker
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

pack 0.14.1

* What buildpacks are you using? Please include versions.

go-build buildpack 0.2.2

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

Custom builder but I believe that's not relevant for this issue.

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

I am trying to move away from `buildpack.yml` since env vars are _the future_ for buildpacks. This was the yml:

```
-go:
-  build:
-    flags:
-    - -ldflags="-extldflags '-f no-PIC -static'"
-    - -tags="osusergo,netgo,embedfs"
```

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by ryanmoran** [comment]
Try the following:
```
pack build my-app --verbose --env BP_GO_BUILD_FLAGS="-ldflags=\"-extldflags '-f no-PIC -static'\" -tags=osusergo,netgo,embedfs"
```

**Comment by genevieve** [comment]
That worked! It might be worth documenting here: https://github.com/paketo-buildpacks/go-build#bp_go_build_flags
