### ISSUE TITLE
We should document quoting BP_GO_BUILD_FLAGS better as its non-trivial

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/go-build#130]
That worked! It might be worth documenting here: https://github.com/paketo-buildpacks/go-build#bp_go_build_flags

_Originally posted by @genevieve in https://github.com/paketo-buildpacks/go-build/issues/129#issuecomment-781699173_

**Comment by fg-j** [comment]
Is escaping quotation marks also required if users specify the `BP_GO_BUILD_FLAGS` env var in a `project.toml`?

**Comment by ForestEckhardt** [comment]
@fg-j I believe you can pass string literals in `toml` but that is worth testing.

**Comment by ForestEckhardt** [comment]
Does paketo-buildpacks/paketo-website#151 resolve this issue?

**Comment by genevieve** [comment]
Works for me!

**Comment by ForestEckhardt** [comment]
Resolved by paketo-buildpacks/paketo-website#151
