### ISSUE TITLE
Feature: register all build targets as launch processes

### ISSUE THREAD

**Issue by wburningham** [paketo-buildpacks/go-build#139]
## What happened?

The `BP_GO_TARGETS` env variable allows for multiple targets (ex: ./cmd/one:./cmd/two)
With a simple project like below:

```go-multiple-targets/
├── cmd
│   ├── one
│   │   └── main.go
│   └── two
│       └── main.go
├── go.mod
```
The buildpack will build both targets, but only register one of them as a launch process.

* What were you attempting to do?
Create a multi process app where I can run either build binary as a process.

* What did you expect to happen?
Running the image with `--entrypoint one` and `--entrypoint two` would run different binaries (the default `web` process would also work [until `web` is no longer set as the default](https://github.com/buildpacks/pack/issues/946))

* What was the actual behavior? Please provide log output, if possible.
Only the `web` process is registered even though multiple binaries exist.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
`pack 0.15.1+git-79adc30.build-1660`

* What buildpacks are you using? Please include versions.
`paketo-buildpacks/go`

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
`io.paketo.stacks.tiny`

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?
```go-multiple-targets/
├── cmd
│   ├── one
│   │   └── main.go
│   └── two
│       └── main.go
├── go.mod
```
with `BP_GO_TARGETS=./cmd/one:./cmd/two`

Discussed on slack [here](https://paketobuildpacks.slack.com/archives/CUEGB5FD1/p1614115627000900)

**Comment by ForestEckhardt** [comment]
@wburningham Would the default entrypoint still be the binary produced from the first target or would there not be any default entrypoint and the end user would have to select an entrypoint from those available?

**Comment by wburningham** [comment]
I would set the first target as the default entrypoint.

**Comment by ForestEckhardt** [comment]
This seems like a great idea then! I am all for it.

**Comment by ForestEckhardt** [comment]
@wburningham I have just put up a [PR](https://github.com/paketo-buildpacks/go-build/pull/142) that I think gets all of your use case. I would love if you could check it out when you have a spare moment
