### ISSUE TITLE
Providing default flags for static builds

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/go-build#140]
## What happened?

* What were you attempting to do?

Trying to wrangle the `BP_GO_BUILD_FLAGS` in a ci config. The quoting was a nightmare.

The go application needs the following build flags:
```
go:
  build:
    flags:
    - -ldflags="-extldflags '-f no-PIC -static'"
    - -tags="osusergo,netgo"
```
This worked fine in the `buildpack.yml` but not so fine in an environment variable situation which is itself passed through a CI config that has surrounding quotes. You might be able to reproduce this yourselves using the pack circleci orb: https://circleci.com/developer/orbs/orb/buildpacks/pack

It accepts arguments as a string in the config so: 
```
build_env: "BP_GO_VERSION=1.16;BP_GO_BUILD_FLAGS=???"
```

Anyway, while trying to get this to work, I was wondering - what exactly do these flags do? I came across a couple things:

https://github.com/golang/go/issues/26492
> Producing a static build with go already requires a non-trivial amount of flags passed to go build, which on Linux currently amounts to something like:
-ldflags '-extldflags "-fno-PIC -static"' -buildmode pie -tags 'osusergo netgo static_build' [1]

https://golang.org/doc/go1.15#linker
https://golang.org/doc/go1.16#linker

I wonder if these are flags that could be supported within the buildpack (in the way that `-buildmode pie` is provided by default.) Perhaps a `BP_GO_BUILD_STATIC` env var that could be a boolean and it turns around and provides these flags by default.

**Comment by ForestEckhardt** [comment]
@genevieve I have a couple of running streams of thought in my head so let me lay them out really quickly. 

1. Is there a reason you can't use `project.toml`, which has a string literal, to set the environment variable literally? 
1. I have concerns about how this would work in tandem with the other environment variables. It seems to be in examining this the only sane way to do this is that if `$BP_GO_BUILD_STATIC` is set that `$BP_GO_BUILD_FALGS` would be locked out. Is that an acceptable trade off for the work y'all are trying to do?
1. Would potentially more specific, yet still generic configuration options help you navigate this better? So if we added something like `$BP_GO_BUILD_LDFLAGS` which would allow you to directly set the value of the `-ldflags` maybe reducing the amount of escaping you need to do.

**Comment by genevieve** [comment]
Hey Forest! 

1. I didn't realize that the `project.toml` replaced functionality available in the `buildpack.yml`? Is the idea that the buildpacks are removing support for `builpack.yml` in favor of the environment variables _and_ the `project.toml`?
2. Yeah that sounds less great.
3. This sounds pretty great.

**Comment by ForestEckhardt** [comment]
To follow up on your question. [`project.toml`](https://buildpacks.io/docs/reference/config/project-descriptor/#example) is a file that is supported by the CNB project that allows you define a variety of things on a per app basis, one of which is build time environment variables. Therefore you can either use the environment variables directly by specifying them in your `pack build` command or they will be injected for you by the lifecycle if they are specified in `project.toml`.

**Comment by genevieve** [comment]
Yeah, I think that'll have to do.
```toml
[[build.env]]
name = "BP_GO_VERSION"
value = "1.16"

[[build.env]]
name = "BP_GO_BUILD_FLAGS"
value = "-ldflags=\"-extldflags '-f no-PIC -static'\" -tags=osusergo,netgo"
```

```bash
Running 'go build -o /layers/paketo-buildpacks_go-build/targets/bin "-ldflags=-extldflags '-f no-PIC -static'" -tags=osusergo,netgo -buildmode pie ./cmd/app'
Completed in 1m44.729s

```
