### ISSUE TITLE
Performance on rebuild for same code

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/go-build#160]
## What happened?

* What were you attempting to do?

Observe the performance times of the buildpacks on rebuilds as we are looking into improved caching in our CI to optimize rebuilds. I noticed the lack of reuse for the go built layer and while the app I tested with is smaller, the times are longer for our larger go apps. I'm curious if there's an explanation for what it does on a rebuild.

* What was the actual behavior? Please provide log output, if possible.

Using a simple public go app (github.com/genevieve/leftovers), I can see the following on the first, second and third runs for the same code. A few buildpack versions ago, I thought I saw the built binary layer being reused instead of rebuilt but (1) I might be recalling incorrectly or (2) perhaps I was setting something else differently.

```bash
pack build leftovers --trust-builder --verbose --timestamps --pull-policy if-not-present
```

1. First
```bash
===> BUILDING
2021/04/09 16:53:46.639929 Paketo Go Distribution Buildpack 0.3.1
  Resolving Go version
    Candidate version sources (in priority order):
      go.mod    -> ">= 1.13"
      <unknown> -> ""

2021/04/09 16:53:46.640386     Selected Go version (using go.mod): 1.16.1

  Executing build process
    Installing Go 1.16.1
2021/04/09 16:53:52.558245       Completed in 5.924s

2021/04/09 16:53:52.592031 Paketo Go Mod Vendor Buildpack 0.2.0
  Skipping build process: modules are already vendored

2021/04/09 16:53:52.612436 Paketo Go Build Buildpack 0.3.0
  Executing build process
    Running 'go build -o /layers/paketo-buildpacks_go-build/targets/bin -buildmode pie ./cmd/leftovers'
2021/04/09 16:54:51.972739       Completed in 59.429s

2021/04/09 16:54:52.822297   Assigning launch processes
    web: /layers/paketo-buildpacks_go-build/targets/bin/leftovers
    leftovers: /layers/paketo-buildpacks_go-build/targets/bin/leftovers
```

2. Second

```bash
2021/04/09 16:43:39.570601 ===> BUILDING
2021/04/09 16:43:39.575728 Paketo Go Distribution Buildpack 0.3.1
  Resolving Go version
    Candidate version sources (in priority order):
      go.mod    -> ">= 1.13"
      <unknown> -> ""

2021/04/09 16:43:39.576195     Selected Go version (using go.mod): 1.16.1

  Reusing cached layer /layers/paketo-buildpacks_go-dist/go

2021/04/09 16:43:39.581538 Paketo Go Mod Vendor Buildpack 0.2.0
  Skipping build process: modules are already vendored

2021/04/09 16:43:39.586750 Paketo Go Build Buildpack 0.3.0
2021/04/09 16:43:39.587122   Executing build process
2021/04/09 16:43:39.587351     Running 'go build -o /layers/paketo-buildpacks_go-build/targets/bin -buildmode pie ./cmd/leftovers'
2021/04/09 16:43:47.081931       Completed in 7.503s

2021/04/09 16:43:47.406799   Assigning launch processes
    web: /layers/paketo-buildpacks_go-build/targets/bin/leftovers
    leftovers: /layers/paketo-buildpacks_go-build/targets/bin/leftovers
```

3. Third

```bash
2021/04/09 16:53:11.746103 ===> BUILDING
2021/04/09 16:53:11.750961 Paketo Go Distribution Buildpack 0.3.1
  Resolving Go version
    Candidate version sources (in priority order):
      go.mod    -> ">= 1.13"
      <unknown> -> ""

2021/04/09 16:53:11.751534     Selected Go version (using go.mod): 1.16.1

  Reusing cached layer /layers/paketo-buildpacks_go-dist/go

2021/04/09 16:53:11.758193 Paketo Go Mod Vendor Buildpack 0.2.0
  Skipping build process: modules are already vendored

2021/04/09 16:53:11.763117 Paketo Go Build Buildpack 0.3.0
2021/04/09 16:53:11.763471   Executing build process
2021/04/09 16:53:11.763657     Running 'go build -o /layers/paketo-buildpacks_go-build/targets/bin -buildmode pie ./cmd/leftovers'
2021/04/09 16:53:21.045786       Completed in 9.292s

2021/04/09 16:53:21.397481   Assigning launch processes
    web: /layers/paketo-buildpacks_go-build/targets/bin/leftovers
    leftovers: /layers/paketo-buildpacks_go-build/targets/bin/leftovers
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

pack v0.18.0

* What buildpacks are you using? Please include versions.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [x] I have included log output.
* [ ] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by fg-j** [comment]
You're right that the buildpack used to sometimes re-use the entire cached layer containing the built binary. There were some bugs with this (e.g #89 and #88) that caused us to switch to not reusing the layer. However, the buildpack does [create a layer for caching built artifacts](https://github.com/paketo-buildpacks/go-build/blob/9ab9c509917b612912bd1b3d2a98df2a8b42e480/build.go#L46) and [passes the layer as the `GOCACHE` to the `go build` call](https://github.com/paketo-buildpacks/go-build/blob/9ab9c509917b612912bd1b3d2a98df2a8b42e480/go_build_process.go#L71). 

So the performance of rebuilds in the buildpack should be about the same as what you'd see building and rebuilding a binary with the go tooling directly.

Are you finding that the rebuild performance isn't fast enough for your use-case?

**Comment by genevieve** [comment]
The issues you linked to make sense. Thank you for the additional context. The rebuild performance is just fine!
