### ISSUE TITLE
Support for single-module multi-image projects

### ISSUE THREAD

**Issue by tylerphelan** [paketo-buildpacks/go-build#19]
We have a project with source code for multiple binaries and we want to build separate images for each binary:

```
go.mod
go.sum
cmd/
├── foo
│   └── main.go
├── bar
│   └── main.go
```

I'm not sure if there is a clean way to configure the buildpack to build `cmd/foo` and `cmd/bar` into separate images using 2 builds with a `buildpack.yml` without changing the source code

**Comment by ryanmoran** [comment]
I think I am missing something here. I think you can do the following:

```
pack build --env BP_GO_TARGETS=./cmd/foo -b gcr.io/paketo-buildpacks/go
pack build --env BP_GO_TARGETS=./cmd/bar -b gcr.io/paketo-buildpacks/go
```

We certainly could do a better job of documenting this.

**Comment by tylerphelan** [comment]
whoops, I thought the env var wasn't supported anymore! that solves our use case.

**Comment by ForestEckhardt** [comment]
I looked into the method about and it will work as long as you either have some `*.go` file at the root of your project or their are targets in you `buildpack.yml` it doesn't appear that `pack` set the env var during the `detect` phase of the buildpack.

**Comment by ryanmoran** [comment]
@ForestEckhardt I think the issue might be here: https://github.com/paketo-buildpacks/go-build/blob/master/build_configuration_parser.go#L22-L24. If the `buildpack.yml` file is missing, then we set targets to `.` always. We should inspect the `$BP_GO_TARGETS` env var in that special case before returning.

**Comment by ForestEckhardt** [comment]
@ryanmoran That's a good catch! I just ran a test to see the `BP_GO_TARGETS` and it is present during the `detect` phase. It appears it is just falling through the cracks. This is absolutely a bug we should fix.
