### ISSUE TITLE
Go build flags slightly unexpected behavior

### ISSUE THREAD

**Issue by tylerphelan** [paketo-buildpacks/go-build#23]
We think this may be a little bit unexpected behavior:

Trying to achieve:

```
go build -ldflags="-X package_path.variable_name=new_value"
```

with `buildpack.yml`

```buildpack.yml
go:
  build:
    flags:
    - -ldflags="-X package_path.variable_name=new_value"
```

Results in this in the logs:

```
go build -ldflags "-X package_path.variable_name=new_value"
```

But we think it's really doing this which doesn't register as a ldflag arg:

```
go build -ldflags "\"-X package_path.variable_name=new_value\""
```

We can use this as a workaround:

```buildpack.yml
go:
  build:
    flags:
    - -ldflags=-X package_path.variable_name=new_value
```

but we should note that the logs after using this look like the below which looks just a little weird without the quotes around the ldflag arg:

```
go build -ldflags -X package_path.variable_name=new_value
```

Also the build fails when we want a space in the `new_value`:

```buildpack.yml
go:
  build:
    flags:
    - -ldflags=-X package_path.variable_name='new value'
```

**Comment by ryanmoran** [comment]
@tylerphelan we believe this is resolved by https://github.com/paketo-buildpacks/go-build/releases/tag/v0.0.17, but please try it out and let us know if you are still seeing issues.

**Comment by tylerphelan** [comment]
works for me

**Comment by tylerphelan** [comment]
@ryanmoran @ForestEckhardt Sorry to come back, but this is failing with build errors with a space in the package variable:

```
go:
  build:
    flags:
      - -ldflags='-X github.com/pivotal/kpack/cmd.Version="2.0.0 foo"'
```

**Comment by ryanmoran** [comment]
@tylerphelan We cannot recreate this in a way that works with `go build`. Can you provide us with a working `go build` command with the correct quoting?

**Comment by tylerphelan** [comment]
Example: `go build -ldflags "-X 'github.com/pivotal/kpack/cmd.Version=2.0.0 foo'"`

but I see now that I was quoting it wrong and it works:
```
go:
  build:
    flags:
    - -ldflags="-X 'github.com/pivotal/kpack/cmd.Version=2.0.0 foo'"
```

Sorry!
