### ISSUE TITLE
Proposal: Add module SBOM generation to this buildpack

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/go-build#256]
I would like to propose adding SBOM generation for golang modules to this buildpack. I propose to achieve this via the SBOM generation feature in packit (once the API for packit is stabilized).

I would have proposed adding it to the `go-mod-vendor` buildpack, except I understand that this wouldn't be possible because the `go-mod-vendor` doesn't write the vendored modules to a layer (because the golang tooling doesn't follow symlinks).

Any concerns with this approach?

@paketo-buildpacks/go-maintainers

**Comment by fg-j** [comment]
I think it would make sense for the `go-mod-vendor` buildpack to generate the BOM and store it in the Build metadata SBOM (rather than a layer SBOM). I think this makes sense because the `go-mod-vendor` buildpack is the one responsible for pulling the go modules into the app workspace.

**Comment by robdimsdale** [comment]
@fg-j and would you then expect the `go-build` buildpack to write the SBOM files in its layer? Or would you not expect it to be present in a layer at all?

**Comment by ryanmoran** [comment]
I agree with @fg-j that the SBOM for the modules should appear in the build metadata for the `go-mod-vendor` buildpack. As for the `go-build` buildpack, that would have its own SBOM. It appears that `syft` is capable of determining the packages used to build a `go` binary. Those SBOMs may have some overlap but would likely be different as the binary would only include those packages that make it into the binary while the `go-mod-vendor` SBOM might include packages like testing libraries or other build-time dependencies.

**Comment by robdimsdale** [comment]
This would form part of the overall SBOM work highlighted in https://github.com/paketo-buildpacks/go/issues/524 and would confirm to [Paketo RFC0038](https://github.com/paketo-buildpacks/rfcs/blob/932d89a970bea06c002496dbd6c7e3812ccab788/text/0038-cdx-syft-sbom.md). The RFC outlines the changes in more detail.

**Comment by fg-j** [comment]
@ryanmoran I've been experimenting with using the `syft` CLI with Go binaries, and I haven't been able to get it working. I left a comment on [this issue](https://github.com/anchore/syft/issues/478#issuecomment-995940653) where they discuss implementing this feature to scan binaries in OCI images.

**Comment by fg-j** [comment]
Implementing this feature is blocked on platform integration issues.
