### ISSUE TITLE
SBOM not being generated

### ISSUE THREAD

**Issue by RealHarshThakur** [paketo-buildpacks/go-build#381]
I'm not using pack CLI/pack client but executing this: `/cnb/lifecycle/creator -app=. imageName`  directly. I expected sbom to generated and embedded in the resulting OCI artifact but couldn't find it. 

## Expected Behavior
Expected SBOM to be present 

## Current Behavior
Cannot find SBOM

## Possible Solution
I'm probably missing some step to produce the SBOM, if so please let me know. Although the build logs say that SBOM was generated but couldn't find them in the location or even in the OCI metadata

**Comment by ryanmoran** [comment]
When you say that you "couldn't find them in the location", where are you looking? The export phase relocates all the SBOM files from each buildpack into a common location at `<layers>/sbom/launch`.

**Comment by natalieparellano** [comment]
Hmm... seeing the (redacted) build logs could be helpful here. Are we expecting to have a launch-level SBOM? It could be that the buildpack is adding an SBOM, but for build-only layers.

@RealHarshThakur since you are using the creator directly can you capture the `<layers>/sbom` directory before the build container exits? You may see SBOM files in `<layers>/sbom/build`.

**Comment by ryanmoran** [comment]
Its worth checking for a build SBOM, but I'm 99% sure we should also be seeing a launch SBOM. The buildpack [marks the layer](https://github.com/paketo-buildpacks/go-build/blob/d1cda661d9cc7f1fa8e5196160809ce9ca04e6ea/build.go#L52) as `launch = true`.

**Comment by RealHarshThakur** [comment]
I'll try to give information as I go. Starting with how I'm using this. 
I'm trying to avoid using pack SDK as it's tied to Docker client and wanted to use buildkit directly. [Dagger](https://dagger.io/) lets me do that. So I'm doing a build via this [method](https://github.com/RealHarshThakur/dagger-builpack/blob/main/pipeline/build.go#L13). 

Build logs:
[log.md](https://github.com/paketo-buildpacks/go-build/files/10170183/log.md)

**Comment by natalieparellano** [comment]
Ah, `CNB_PLATFORM_API` is probably the reason. If it is not set, the lifecycle will default to Platform API 0.3, which doesn't support SBOM. Can you try setting it to 0.8 or higher?

**Comment by RealHarshThakur** [comment]
Thanks a lot @natalieparellano @ryanmoran. That fixed it :)
