### ISSUE TITLE
Could this buildpack look for the main pkg in the cmd dir in addition to the root?

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/go-build#71]
We have a number of Go applications that follow the convention of having the main pkg inside of `cmd/*` subdirectory. This would require us to add a `buildpack.yaml` to each of these application repositories to specify that the target is in that directory instead of at the root.

Since this is a fairly common pattern in Go codebases, would this be something the buildpack could support by default? i.e. searching through the `cmd` directory for the main package.

**Comment by ForestEckhardt** [comment]
I cannot think of any strong argument against this idea. It seems like fairly common pattern and something that would benefit user greatly if we supported it.

**Comment by ryanmoran** [comment]
This is now the behavior in `gcr.io/paketo-buildpacks/go:0.2.4`. Let us know if this works for your use-case.

**Comment by genevieve** [comment]
This works for our usecase! Thank you!!
